---
version: "3.9"

services:
  sanaii:
    image: ghcr.io/Itproexpert/sanaii:latest
    container_name: sanaii
    hostname: yourhostname
    volumes:
      - $PWD/db/:/etc/x-ui/
      - $PWD/cert/:/root/cert/
    environment:
      XRAY_VMESS_AEAD_FORCED: "false"
    tty: true
    network_mode: host
    restart: unless-stopped
